site_name: BlastOff documentation
nav: 
- Home: index.md
- Introduction: introduction.md
- Smart Contracts: 
  - Overview: contracts/overview.md
  - Governance: contracts/governance.md
  - Future Yield Minting Vault: contracts/mint-vault.md
  - Staking Vault: contracts/staking-vault.md
  - IDO Pool For Future Yield: contracts/ido.md

theme: readthedocs