site_name: BlastOff documentation
nav: 
- Home: index.md
- Introduction: introduction.md
- Smart Contracts: 
  - Overview: contracts/overview.md
  - Governance: contracts/governance.md
  - Future Yield Minting Vault: contracts/mint-vault.md
  - Staking Vault: contracts/staking-vault.md
  - IDO Pool For Future Yield: contracts/ido.md
  - Deployed Contracts: contracts/deployed.md
theme: readthedocs
use_directory_urls: false
plugins:
  - search
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
